services:
  - type: web
    name: swing-stockpicker
    runtime: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ANGELONE_API_KEY
        sync: false
      - key: ANGELONE_CLIENT_ID
        sync: false
      - key: ANGELONE_PASSWORD
        sync: false
      - key: ANGELONE_TOTP_SECRET
        sync: false
